[tool.poetry]
name = "curious"
version = "0.1.0"
description = "A curious llm"
authors = ["RobbenRibery <runodng.liu@outlook.com>"]
license = "Apache-2.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python-dotenv = "^1.0.1"
python = ">=3.11.0,<3.14"
torch = "^2.6.0"
transformers = "^4.49.0"
toml = "^0.10.2"
wandb = "^0.19.7"
datasets = "^3.3.2"
unidiff = "^0.7.5"
diff-parser = "^1.1"
tree-sitter = "^0.24.0"
accelerate = ">=0.26.0"
tyro = "^0.9.17"
setuptools = "^76.0.0"
math-verify = "^0.7.0"
memory-profiler = "^0.61.0"
trl = "^0.16.1"
liger-kernel = "^0.5.7"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
generate-setup-file = true