#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Share the CISPO config; override AD-CISPO identity plus the safer 1.7B comparison knobs.
export RUN_NAME="${RUN_NAME:-gsm8k-ad-cispo-qwen3-1p7b-causal-tangent-smoothed-top4-max1p5-b160-v1}"
export WANDB_GROUP="${WANDB_GROUP:-ad-cispo-gsm8k}"
export OBJECTIVE_NAME="AD-CISPO"
export USE_CISPO_LOSS="1"
export USE_AD_CISPO="1"
export MODEL_NAME="${MODEL_NAME:-Qwen/Qwen3-1.7B}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-32}"
export GROUP_SIZE="${GROUP_SIZE:-8}"
export MINI_BATCH_SIZE="${MINI_BATCH_SIZE:-32}"
export BACKWARD_MICRO_BATCH_SIZE="${BACKWARD_MICRO_BATCH_SIZE:-8}"
export LOGITS_MINIBATCH_SIZE="${LOGITS_MINIBATCH_SIZE:-8}"
export EPOCHS_PER_STEP="${EPOCHS_PER_STEP:-1}"
export MAX_TRAIN_BATCHES="${MAX_TRAIN_BATCHES:-160}"
export EVAL_INTERVAL="${EVAL_INTERVAL:-20}"
export MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-1536}"
export SGLANG_MEM_FRACTION_STATIC="${SGLANG_MEM_FRACTION_STATIC:-0.12}"
export SGLANG_REQUEST_BATCH_SIZE="${SGLANG_REQUEST_BATCH_SIZE:-8}"
export COMPILE_TRAIN_MODEL="${COMPILE_TRAIN_MODEL:-0}"
export AD_CISPO_SALIENCY_METHOD="${AD_CISPO_SALIENCY_METHOD:-causal_tangent_smoothed}"
export AD_CISPO_TOP_LAYERS="${AD_CISPO_TOP_LAYERS:-4}"
export AD_CISPO_MIN_MULTIPLIER="${AD_CISPO_MIN_MULTIPLIER:-0.25}"
export AD_CISPO_MAX_MULTIPLIER="${AD_CISPO_MAX_MULTIPLIER:-1.5}"
export AD_CISPO_EPS="${AD_CISPO_EPS:-1e-8}"
export AD_CISPO_ATTENTION_BLOCK_SIZE="${AD_CISPO_ATTENTION_BLOCK_SIZE:-128}"

exec "${SCRIPT_DIR}/launch_baseline_gsm8k_training_modal.sh" "$@"
